---
title: "Olfaction Data"
author: "Vidya Koesmahargyo"
date: "10/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading in the data:
```{r Load Libraries, message=FALSE, warning=FALSE}
library(dplyr)
library(tibble)
library(ggplot2)
library(ggfortify)
library(OpenImageR)
library(fastICA)
library(NMF)

```

```{r Load Data}

# Molecuar data and labels
molec_desc <- read.delim('molecular_descriptors.txt', stringsAsFactors = FALSE)
labels <- read.delim("training_set.txt", stringsAsFactors = FALSE)

# Examine data
head(molec_desc)
dim(molec_desc)
str(molec_desc)

head(labels)
dim(labels)
str(labels)

```

```{r Check NAs}

# Check for NA values
any(is.na(molec_desc))

# Get colnames and number of NAs
na_lst <- sapply(molec_desc, function(x) sum(is.na(x)))

# Cols missing 2 or more
na_lst_1 <- subset(na_lst, na_lst > 1)

# Cols missing 3 or more
na_lst_2 <- subset(na_lst, na_lst > 2)

# Cols missing 4 or more
na_lst_3 <- subset(na_lst, na_lst > 3)

# Print total number of columns with varying amount of NAs
sum(na_lst) # 1+ NA
sum(na_lst_1) # 2+ NA
sum(na_lst_2) # 3+ NA
sum(na_lst_3) # 4+ NA ... there are none

# Find sum of NAs by row
na_row_lst <- apply(molec_desc, MARGIN = 1, function(x) sum(is.na(x)))

# Find row with NAs
row_na <- as.vector(which(na_row_lst > 0 %in% molec_desc))

# Show rows in molec_desc with NAs and count
(na_row_table <- cbind("Row Index" = row_na, "Total NAs" = na_row_lst[row_na]))
```



```{r Pre-process data}

# Remove rows with NA values
molec_desc <- na.omit(molec_desc)

# Remove columns with no variance
molec_desc <- molec_desc[ ,(apply(molec_desc,2,var)!=0)]

```


```{r Pre-process labels}

# Make factors
labels$VALENCE.PLEASANTNESS <- factor(labels$VALENCE.PLEASANTNESS)
levels(labels$VALENCE.PLEASANTNESS) <- list("Unpleasent" = c(0:33), "Neutral" = c(34:66), "Pleasant" = c(67:100))

labels$INTENSITY.STRENGTH <- factor(labels$INTENSITY.STRENGTH)
levels(labels$INTENSITY.STRENGTH) <- list("Low" = c(0:33), "Medium" = c(34:66), "High" = c(67:100))

# Subset
olfaction_data <- subset(labels, Intensity == "high ", select = c("Compound.Identifier", "Odor", "VALENCE.PLEASANTNESS", "INTENSITY.STRENGTH"))

# Rename Compound Identifier column
#colnames(olfaction_data)[1] <- "CID"

# Examine new dataframe
dim(olfaction_data)
str(olfaction_data)

```


```{r New dataframe with data and labels}

# Rename Compound Identifier column
colnames(olfaction_data)[1] <- "CID"

# Merge data and labels
total_olfac <- merge(x = molec_desc, y = olfaction_data, by= "CID", all.y = TRUE)

# Examine data
head(total_olfac)
dim(total_olfac)


```


```{r Bar Plots}

# Visualize some data

# Intensity
ggplot(total_olfac) + geom_bar(aes(x=INTENSITY.STRENGTH, fill = INTENSITY.STRENGTH)) + ggtitle("Distribution of Perceived Odor Intensity") + xlab("Odor Intensity")

# Valence
ggplot(total_olfac) + geom_bar(aes(x=VALENCE.PLEASANTNESS, fill = VALENCE.PLEASANTNESS)) + ggtitle("Distribution of Odor Pleasantness") + xlab("Odor Pleasantness")

# Intensity of Valence
ggplot(total_olfac) + geom_bar(aes(x=VALENCE.PLEASANTNESS, fill = INTENSITY.STRENGTH)) + ggtitle("Perceived Intensity of Odor Pleasantness") + xlab("Odor Pleasantness")

```

```{r Near Zero Variance}

#variance selection: near zero variance
nzv <- nearZeroVar(molec_desc_pca, saveMetrics= TRUE)
nzv[nzv$nzv,]
molec_desc_pca$nTB

#look at each nzv descriptor and select more closely
filtered_molec_desc <- molec_desc_pca[unlist(nzv)]
dim(filtered_molec_desc)
```


PCA of molecular descriptor data
```{r PCA}

# Create new tibble for PCA
molec_desc_pca <- as.tibble(molec_desc)

# Setting the CID column separately
identifiers <- molec_desc_pca[ , 1]
# Setting all other columns
molec_desc_pca <- molec_desc_pca[ , 2:ncol(molec_desc_pca) ] 

# Scaling pca
pca <- prcomp(molec_desc_pca, scale. = T) 

# Plot PCA and Screeplot
autoplot(pca)
screeplot(pca, 100, main='Screeplot of Olfaction data', type='l')

## Cumulative scree plot
std_dev <- pca$sdev
pr_var <- std_dev^2
prop_varex <- pr_var/sum(pr_var)
plot(cumsum(prop_varex), type='b', main="Cumulative Sum Screeplot", xlab='Principle Component', ylab='Total Variance Proportion')

```


```{r }
print(tail(colnames(total_olfac)))
```

```{r }
labels <- total_olfac$Odor

olfac_no_label <- subset(total_olfac, select = -c(1, 3076, 30))

set.seed(1000009)
km <- kmeans(olfac_no_label, 471, nstart=20)

print(km$centers)

```


```{r}
library(factoextra)
#fviz_eig(pca)
#fviz_pca_var(pca,col.var = 'contrib',  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel=TRUE)
#fviz_pca_biplot(pca, repel = TRUE,col.var = "#2E9FDF",col.ind = "#696969")
```

